package com.shashi.coffeemachine;

import com.shashi.coffeemachine.data.AppConfiguration;
import com.shashi.coffeemachine.data.ConfigurationReadable;
import com.shashi.coffeemachine.data.impl.JsonConfigurationReadableImpl;
import com.shashi.coffeemachine.data.MachineConfiguration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);
    private static final String configurationFileName = "sampleData.json";

    public static void main(String[] args) {
        logger.debug("Starting Main method.");
        ConfigurationReadable configurationReadable = new JsonConfigurationReadableImpl(configurationFileName);
        AppConfiguration appConfiguration = configurationReadable.getConfiguration();
        MachineConfiguration machineConfiguration = appConfiguration.getMachineConfiguration();
        CoffeeMachineApp app = new CoffeeMachineApp(machineConfiguration);
        app.start();
    }
}
